### ISSUE TITLE
There is no about.js in the getting started branch

### ISSUE THREAD

**Issue by shanselman** [arunoda/learnnextjs-demo#1]
At this point in the tutorial https://learnnextjs.com/basics/navigate-between-pages/using-link , you're asked to click the About Page (referring to the one you created before) except you've made a NEW folder and cloned `git clone https://github.com/arunoda/learnnextjs-demo.git`

There is no about.js yet, but the tutorial assumes it. Perhaps add it to this branch at this point.

**Comment by arunoda** [comment]
Yep. I just added that file.
Thanks for notifying me.

**Comment by shanselman** [comment]
Thanks for a brilliant tutorial! Your work is appreciated.
