### ISSUE TITLE
'npm run build' fails

### ISSUE THREAD

**Issue by PDXIII** [arunoda/learnnextjs-demo#10]
I followed your “learn next.js” tutorial which worked out pretty fine but a few days later I wanted to try our the build process without ```now``` so I tried ```npm run build``` aka ```next build``` and it ended with this error:

### Error Console Output

    Error: ./pages/batman-shows.js?entry
    Module build failed: SyntaxError: unknown: Unexpected token (5:25)
      3 | import fetch from 'isomorphic-fetch';
      4 |
    > 5 | export default (props => <BasicLayout>
        |                          ^
      6 |     <h1>Batman Shows</h1>
      7 |     <ul>
      8 |       {props.shows.map(({ show }) => <li key={show.id}>

Which is kind of strange because the original code looks like this:

### My Source Code

    import BasicLayout from '../layouts/BasicLayout'
    import Link from 'next/link'
    import fetch from 'isomorphic-fetch'

    export default (props) => (
      <BasicLayout>
        <h1>Batman Shows</h1>
        <ul>
          { props.shows.map(({ show }) => (
            <li key={ show.id }>
              <Link
                as={`/s/${ show.id }`}
                href={`/show?id=${ show.id }`}>
                  <a>{ show.name }</a>
                </Link>
            </li>
          ))}
        </ul>
      </BasicLayout>
    )
    .getInitialProps = async () => {
      const res = await fetch('http://api.tvmaze.com/search/shows?q=batman')
      const data = await res.json()

      console.log(`Show data fetched. Count: ${data.length}`)

      return {
        shows:data
      }
    }

The app works fine when started with ```npm start```. Any ideas?

### Update

Even when I try to run it with ```npm run dev``` it shows the same error.

**Comment by arunoda** [comment]
Look at the error message, the syntax is incorrect. It's not the same as the original.

**Comment by PDXIII** [comment]
That's what I am wondering about. Why does the compile process strip away these parenthesis?

**Comment by PDXIII** [comment]
Hi @arunoda!

Thank you for your fast reply and sorry for bothering you once more but to be clear: the above code is the error message and the code below is my source code. How come that the compile process removes the parenthesis?

**Comment by simoroshka** [comment]
@PDXIII they are seen as not necessary since you are using implicit return. They are removed in the translation process, I guess. But the problem is you cannot add the getInitialProps function this way, it is incorrect use of chaining. If you check, the function is going to be undefined. Write the code more explicitly, don't try to mix everything in one expression.
