### ISSUE TITLE
[Create Dynamic Pages] - Missing '../components/MyLayout.js'

### ISSUE THREAD

**Issue by jvaloria** [arunoda/learnnextjs-demo#20]
Hi! I'm missing a component, not sure if I should create it myself or if it should be part of this repo by default.

Tutorial URL: https://learnnextjs.com/basics/create-dynamic-pages/adding-a-list-of-posts

Tutorial Step: Adding a list of posts

Problem: Requested to import a missing component
`import Layout from '../components/MyLayout.js'`

No `/components/MyLayout.js` is included by default. 

Is this expected?

Thank you!

**Comment by jvaloria** [comment]
My Bad, forgot to checkout the correct branch `using-shared-components`

**Comment by kr1st1n4gr03g3r** [comment]
It should be mentioned in the tutorial to use different branches. This isn't totally clear. <3 https://github.com/arunoda/learnnextjs-demo/branches
