### ISSUE TITLE
please check this repo, many branch can not run

### ISSUE THREAD

**Issue by ruoru** [arunoda/learnnextjs-demo#30]

**Comment by scc02** [comment]
such as branch using-shared-components

**Comment by timneutkens** [comment]
I just went through them all, and they all seem to run fine 🤔

**Comment by ruoru** [comment]
@timneutkens like brach `clean-urls-ssr`, the code is different for [next.js org demo code](https://nextjs.org/learn/basics/fetching-data-for-pages/setup). and you may check next version, and try again. 
my next package version is 6.1.1
node version is 10^
macOS 10.13.x
