### ISSUE TITLE
Error When Clicking next/Links

### ISSUE THREAD

**Issue by cdnadmin** [arunoda/learnnextjs-demo#34]
I get the following when I click any of the `next/Link` links: 

> deepForceUpdate is not a function
>
> TypeError: deepForceUpdate is not a function
>....at AppContainer.componentWillReceiveProps (http://localhost:3000/_next/1535290661890/main.js:19058:7)
....at callComponentWillReceiveProps (http://localhost:3000/_next/1535290661890/commons.js:11534:14)
....at updateClassInstance (http://localhost:3000/_next/1535290661890/commons.js:11726:7)
....at updateClassComponent (http://localhost:3000/_next/1535290661890/commons.js:13160:20)
....at beginWork (http://localhost:3000/_next/1535290661890/commons.js:13831:14)
....at performUnitOfWork (http://localhost:3000/_next/1535290661890/commons.js:15870:12)
....at workLoop (http://localhost:3000/_next/1535290661890/commons.js:15909:24)
....at renderRoot (http://localhost:3000/_next/1535290661890/commons.js:15949:7)
....at performWorkOnRoot (http://localhost:3000/_next/1535290661890/commons.js:16567:22)
....at performWork (http://localhost:3000/_next/1535290661890/commons.js:16489:7)
>
>    in AppContainer (created by Container)
    in Container (created by App)
    in div (created by App)
    in App`

Tried updating `package.json` to use `"next": "^6.1.1"` and `"react": "^16.4.0"` to no avail.

Please note that this error occurs only when the rendered hyper link is clicked.  It goes away if I hard-reload the page.  But, of course, this defeats the purpose (in addition to being an error).

**Comment by timneutkens** [comment]
Same as https://spectrum.chat/thread/5f3d8900-8912-48d9-a0b1-3d8116c31a6c

**Comment by cdnadmin** [comment]
Indeed. Thx for closing issue.
