### ISSUE TITLE
[Question] «Build your app locally» section not clear enough. Care to clarify?

### ISSUE THREAD

**Issue by soulchainer** [arunoda/learnnextjs-demo#8]
[This section](https://learnnextjs.com/basics/deploying-a-nextjs-app/build-your-app-locally) states:

> ▲ZEIT now will detect the “npm build” script and build it for you when you deploy.
>
> Some hosting providers do not have something like that. In that case, you can build your app locally with:
>
> `npm run build`
>
> Then deploy the app with the `.next` directory and only keep the `start` npm command in your `package.json`.

But it doesn't seem pretty clear to me. I mean, the last phrase.

> with the `.next` directory

This means you need to include `.next`, together with the rest, when deploying? This mean you need to use `now` from inside of `.next`? Or what?

> only keep the `start` npm command in your `package.json`

¿? Delete all the other scripts from `package.json`? And them needing to do them manually every time? Or what?

Thanks for your time :).

**Note**: I will still be trying ZEIT now, but I also want to understand this well.

**Comment by arunoda** [comment]
This is not about deploying to `now`. But into some other service. I can make this more clear.

**Comment by arunoda** [comment]
I hope now it's clear.
![screen shot 2017-06-10 at 10 57 10 am](https://user-images.githubusercontent.com/50838/27000269-9de1d396-4dcb-11e7-82db-090cc2ce3b04.png)
