### ISSUE TITLE
Markdown component

### ISSUE THREAD

**Issue by justswim** [arunoda/learnnextjs-demo#9]
The <Markdown> component in 'Styling components' is not clearly documented in the tutorial. https://learnnextjs.com/basics/styling-components/global-styles

In fact there is no page that describes what the Markdown component should be or what it means. I eventually figured it out by digging in a later branch of the repo, but could we add a bit more info on that component?

**Comment by arunoda** [comment]
If you download the source code from [here](https://learnnextjs.com/basics/styling-components/setup), the component will be there.

But I'll try to make it a bit simple by using a markdown component from NPM.

**Comment by arunoda** [comment]
Check now: https://learnnextjs.com/basics/styling-components/global-styles
Now we are using a markdown component from NPM.
